[package]
name = "cirious_gui"
version = "0.1.0"
authors = ["CiberCodes <tuliosouza0803@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.34.5"
default-features = false
features = ["image", "ttf"]
